CREATE TABLE categories (
    id          BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(100) NOT NULL,
    description VARCHAR(500),
    version     BIGINT       NOT NULL DEFAULT 0,
    created_at  TIMESTAMPTZ  NOT NULL,
    updated_at  TIMESTAMPTZ  NOT NULL,
    CONSTRAINT uk_categories_name UNIQUE (name)
);

-- Nullable: product co the chua duoc phan loai, va de khong pha vo du lieu dang co.
ALTER TABLE products
    ADD COLUMN category_id BIGINT;

ALTER TABLE products
    ADD CONSTRAINT fk_products_category
        FOREIGN KEY (category_id) REFERENCES categories (id);

-- PostgreSQL KHONG tu tao index cho cot FK. Thieu index nay thi moi lan xoa/sua
-- categories se phai seq scan ca bang products de kiem tra rang buoc.
CREATE INDEX idx_products_category_id ON products (category_id);
