CREATE TABLE users (
    id          BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username    VARCHAR(200) NOT NULL,
    password    VARCHAR(200) NOT NULL,
    role        VARCHAR(50)  NOT NULL,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT uk_users_username UNIQUE (username)
);
